### ISSUE TITLE
not giving result

### ISSUE THREAD

**Issue by ArslanMazhar** [jeffbuffs/Waytime#3]
i have run the tool with some multiple domain and a single domain but after taking to much time it can't give any result
![1](https://github.com/CVOP-Computer-Vision-OPS/Waytime/assets/48792133/c5703e85-4817-4af7-b71e-5130a13e5995)

**Comment by jeffbuffs** [comment]
Can you gave me more context like the format of domains you provided

**Comment by jeffbuffs** [comment]
Closing the issue. You were blocked from the Wayback API URL. If you disagree, feel free to reopen it
![2](https://github.com/CVOP-Computer-Vision-OPS/Waytime/assets/71769599/5d258ab7-c1e0-4074-8f68-70bdea21825f)


You Can Use VPN or Some Proxies to get rid of it and Use Waytime and Other tool like waybackurls .
